name: Hello world
author: Prem Prakash
description: Some description
inputs:
    who-to-greet:
        description: "who to greet"
        required: true
        default: Prem

outputs:
    time:
        description: "The greeting time"

runs:
    using: "docker"
    image: "dist/index.js"
    args:
        - $ {{ inputs.who-to-greet }}
